# Generated by Django 5.1 on 2024-09-06 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('alpha_num_id', models.CharField(max_length=10, unique=True)),
                ('caste', models.CharField(max_length=100)),
                ('sub_caste', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('siblings_count', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')])),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('education', models.CharField(max_length=500)),
                ('hobbies', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('special_request', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.TextField(max_length=2000)),
                ('city', models.CharField(max_length=50)),
                ('primary_mobile_no', models.CharField(default='', max_length=20, unique=True)),
                ('primary_email_id', models.CharField(default='', max_length=100, unique=True)),
                ('secondary_mobile_no', models.CharField(default='', max_length=20)),
                ('secondary_email_id', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
